### ISSUE TITLE
Is this a port 8080 issue?

### ISSUE THREAD

**Issue by genemang** [neubot/neubot#28]
2015-12-15 16:20:10	ERROR	isconnected(): connect() to neubot.mlab.mlab3.nuq02.measurement-lab.org:8080 failed
2015-12-15 16:20:10	ERROR	Traceback (most recent call last):
2015-12-15 16:20:10	ERROR	File "/usr/local/share/neubot/0.004016009/neubot/utils_net.py", line 230, in isconnected
2015-12-15 16:20:10	ERROR	sock.recv(1024)
2015-12-15 16:20:10	ERROR	error: [Errno 51] Network is unreachable
2015-12-15 16:20:10	ERROR	* speedtest: connection failed

**Comment by btilford** [comment]
Min errors out on port 80

```
2016-01-19 21:47:51	ERROR	connect(): cannot connect to neubot.mlab.mlab2.ord01.measurement-lab.org:80
2016-01-19 21:47:51	ERROR	Traceback (most recent call last):
2016-01-19 21:47:51	ERROR	File "/usr/share/neubot/neubot/utils_net.py", line 164, in connect
2016-01-19 21:47:51	ERROR	socket.SOCK_STREAM)
2016-01-19 21:47:51	ERROR	gaierror: [Errno -3] Temporary failure in name resolution
```
