### ISSUE TITLE
Does not install on MacOS Sierra

### ISSUE THREAD

**Issue by pskowronek** [neubot/neubot#34]
Does not install on MacOS Sierra - the installer fails with: "The installation did not succeed".

**Comment by bassosimone** [comment]
Ouch, that's definitely not explanatory at all. I'll upgrade to Sierra (I am still using the previous macOS) and see for myself. (I am anyway trying to rewrite Neubot splitting the core and the tests in a way that should be easier to deal with and in that process I'll also try to release it as an app in the store, to get rid of problems like this in the future.)

**Comment by qayshp** [comment]
It also fails to start up if already installed and you upgrade to Sierra.
The main error seems to be related to user `_neubot`.
```
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR: RuntimeError: utils_posix: getpwnam(): "_neubot": no such user
```

Here's the full install log from my recently upgraded MacBook Pro:
```
Aug 25 12:28:07 qayshp Installer[14522]: @(#)PROGRAM:Install  PROJECT:Install-1000
Aug 25 12:28:07 qayshp Installer[14522]: @(#)PROGRAM:Installer  PROJECT:Installer-909
Aug 25 12:28:07 qayshp Installer[14522]: Hardware: MacBookPro11,5 @ 2.80 GHz (x 8), 16384 MB RAM
Aug 25 12:28:07 qayshp Installer[14522]: Running OS Build: Mac OS X 10.12.6 (16G29)
Aug 25 12:28:07 qayshp Installer[14522]: Env: TMPDIR=/var/folders/zn/xrv_c6bd3cq5mxkzn0qh0tmw0000gn/T/
Aug 25 12:28:07 qayshp Installer[14522]: Env: __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
Aug 25 12:28:07 qayshp Installer[14522]: Env: HOME=/Users/qayshp
Aug 25 12:28:07 qayshp Installer[14522]: Env: SHELL=/usr/local/bin/zsh
Aug 25 12:28:07 qayshp Installer[14522]: Env: Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.eVrALxZoSi/Render
Aug 25 12:28:07 qayshp Installer[14522]: Env: SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.fs100A4tUM/Listeners
Aug 25 12:28:07 qayshp Installer[14522]: Env: PATH=/usr/bin:/bin:/usr/sbin:/sbin
Aug 25 12:28:07 qayshp Installer[14522]: Env: LOGNAME=qayshp
Aug 25 12:28:07 qayshp Installer[14522]: Env: DISPLAY=/private/tmp/com.apple.launchd.VpJg60tnTt/org.macosforge.xquartz:0
Aug 25 12:28:07 qayshp Installer[14522]: Env: XPC_SERVICE_NAME=com.apple.installer.460
Aug 25 12:28:07 qayshp Installer[14522]: Env: USER=qayshp
Aug 25 12:28:07 qayshp Installer[14522]: Env: XPC_FLAGS=0x0
Aug 25 12:28:07 qayshp Installer[14522]: neubot-0.4.16.9  Installation Log
Aug 25 12:28:07 qayshp Installer[14522]: Opened from: /Users/qayshp/Downloads/neubot-0.4.16.9.pkg
Aug 25 12:28:07 qayshp Installer[14522]: Referenced component packages (1) trustLevel=100
Aug 25 12:28:21 qayshp Installer[14522]: InstallerStatusNotifications plugin loaded
Aug 25 12:28:29 qayshp Installer[14522]: Administrator authorization granted.
Aug 25 12:28:29 qayshp Installer[14522]: ================================================================================
Aug 25 12:28:29 qayshp Installer[14522]: User picked Standard Install
Aug 25 12:28:29 qayshp Installer[14522]: Choices selected for installation:
Aug 25 12:28:29 qayshp Installer[14522]: 	Upgrade: "neubot-0.4.16.9"
Aug 25 12:28:29 qayshp Installer[14522]: 		neubot-0.4.16.9.pkg : org.neubot : 0.4.15.0.4
Aug 25 12:28:29 qayshp Installer[14522]: ================================================================================
Aug 25 12:28:29 qayshp Installer[14522]: It took 0.00 seconds to summarize the package selections.
Aug 25 12:28:29 qayshp Installer[14522]: -[IFPKGDerivedDocument sortedPackageLocations]: result = (
	    "file://localhost"
	)
Aug 25 12:28:29 qayshp Installer[14522]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Aug 25 12:28:29 qayshp Installer[14522]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/qayshp/Downloads/neubot-0.4.16.9.pkg
Aug 25 12:28:29 qayshp Installer[14522]: Set authorization level to root for session
Aug 25 12:28:29 qayshp Installer[14522]: Will use PK session
Aug 25 12:28:29 qayshp Installer[14522]: Using authorization level of root for IFPKInstallElement
Aug 25 12:28:29 qayshp Installer[14522]: Starting installation:
Aug 25 12:28:29 qayshp Installer[14522]: Configuring volume "Macintosh HD"
Aug 25 12:28:29 qayshp Installer[14522]: Preparing disk for local booted install.
Aug 25 12:28:29 qayshp Installer[14522]: Free space on "Macintosh HD": 425.63 GB (425626411008 bytes).
Aug 25 12:28:29 qayshp Installer[14522]: Create temporary directory "/var/folders/zn/xrv_c6bd3cq5mxkzn0qh0tmw0000gn/T//Install.14522fOIfQ3"
Aug 25 12:28:29 qayshp Installer[14522]: IFPKInstallElement (1 packages)
Aug 25 12:28:29 qayshp installd[558]: PackageKit: Adding client PKInstallDaemonClient pid=14522, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Aug 25 12:28:29 qayshp Installer[14522]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Aug 25 12:28:29 qayshp installd[558]: PackageKit: ----- Begin install -----
Aug 25 12:28:29 qayshp installd[558]: PackageKit: request=PKInstallRequest <1 packages, destination=/>
Aug 25 12:28:29 qayshp installd[558]: PackageKit: packages=(
	    "PKJaguarPackage <file://localhost/Users/qayshp/Downloads/neubot-0.4.16.9.pkg>"
	)
Aug 25 12:28:29 qayshp installd[558]: PackageKit: Session UUID file exists - will not overwrite /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/852F5930-D3F9-4E59-9CA0-518ED598FA2D.activeSandbox
Aug 25 12:28:30 qayshp installd[558]: PackageKit: Will do receipt-based obsoleting for package identifier org.neubot (prefix path=usr/local/share)
Aug 25 12:28:30 qayshp installd[558]: PackageKit: Extracting file://localhost/Users/qayshp/Downloads/neubot-0.4.16.9.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/852F5930-D3F9-4E59-9CA0-518ED598FA2D.activeSandbox/Root/usr/local/share, uid=0)
Aug 25 12:28:31 qayshp installd[558]: PackageKit: prevent user idle system sleep
Aug 25 12:28:31 qayshp installd[558]: PackageKit: suspending backupd
Aug 25 12:28:31 qayshp install_monitor[14548]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Aug 25 12:28:31 qayshp installd[558]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/852F5930-D3F9-4E59-9CA0-518ED598FA2D.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/852F5930-D3F9-4E59-9CA0-518ED598FA2D.activeSandbox
Aug 25 12:28:31 qayshp installd[558]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/852F5930-D3F9-4E59-9CA0-518ED598FA2D.activeSandbox/Root (1 items) to /
Aug 25 12:28:31 qayshp installd[558]: PackageKit: Executing script "./postflight" in /Users/qayshp/Downloads/neubot-0.4.16.9.pkg/Contents/Resources
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR: unhandled exception
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR: Traceback (most recent call last):
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:   File "/usr/local/share/neubot/0.004016009/neubot/privacy.py", line 109, in main
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:     __main(args)
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:   File "/usr/local/share/neubot/0.004016009/neubot/privacy.py", line 214, in __main
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:     connection = DATABASE.connection()
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:   File "/usr/local/share/neubot/0.004016009/neubot/database/__init__.py", line 62, in connection
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:     self.path = system.check_database_path(self.path)
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:   File "/usr/local/share/neubot/0.004016009/neubot/system.py", line 62, in check_database_path
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:     _want_rwx_dir(os.path.dirname(pathname))
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:   File "/usr/local/share/neubot/0.004016009/neubot/system_posix.py", line 90, in _want_rwx_dir
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:     passwd = getpwnam()
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:   File "/usr/local/share/neubot/0.004016009/neubot/system_posix.py", line 101, in getpwnam
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:     passwd = utils_posix.getpwnam(unpriv_user)
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:   File "/usr/local/share/neubot/0.004016009/neubot/utils_posix.py", line 299, in getpwnam
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR:     uname)
Aug 25 12:28:32 qayshp installd[558]: ./postflight: ERROR: RuntimeError: utils_posix: getpwnam(): "_neubot": no such user
Aug 25 12:28:32 qayshp install_monitor[14548]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Aug 25 12:28:33 qayshp installd[558]: PackageKit: releasing backupd
Aug 25 12:28:33 qayshp installd[558]: PackageKit: allow user idle system sleep
Aug 25 12:28:33 qayshp installd[558]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “neubot-0.4.16.9.pkg”." UserInfo={NSFilePath=./postflight, NSURL=file://localhost/Users/qayshp/Downloads/neubot-0.4.16.9.pkg, PKInstallPackageIdentifier=org.neubot, NSLocalizedDescription=An error occurred while running scripts from the package “neubot-0.4.16.9.pkg”.} {
	    NSFilePath = "./postflight";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cneubot-0.4.16.9.pkg\U201d.";
	    NSURL = "file://localhost/Users/qayshp/Downloads/neubot-0.4.16.9.pkg";
	    PKInstallPackageIdentifier = "org.neubot";
	}
Aug 25 12:28:33 qayshp installd[558]: PackageKit: Running idle tasks
Aug 25 12:28:33 qayshp Installer[14522]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “neubot-0.4.16.9.pkg”." UserInfo={NSFilePath=./postflight, NSURL=file://localhost/Users/qayshp/Downloads/neubot-0.4.16.9.pkg, PKInstallPackageIdentifier=org.neubot, NSLocalizedDescription=An error occurred while running scripts from the package “neubot-0.4.16.9.pkg”.}
Aug 25 12:28:33 qayshp installd[558]: PackageKit: Removing client PKInstallDaemonClient pid=14522, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Aug 25 12:28:33 qayshp installd[558]: PackageKit: Done with sandbox removals
Aug 25 12:28:33 qayshp Installer[14522]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Aug 25 12:28:33 qayshp Installer[14522]: IFDInstallController 5810 state = 8
Aug 25 12:28:33 qayshp Installer[14522]: Displaying 'Install Failed' UI.
Aug 25 12:28:33 qayshp Installer[14522]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
```

**Comment by qayshp** [comment]
Verified with `dscl . -ls /Users` that there is no _neubot user 😕

**Comment by qayshp** [comment]
Hmmm, two things:

1. After trying again on a different machine with Sierra, it seems to work fine. I'm not sure exactly what all the differences are, but a clear one is that the one where it failed is joined to a domain while the one where it succeeded is not. I would love to know what others are seeing.
2. If this bug is still valid given (1) above, I think this issue actually belongs on the repository specific to the [Mac port of NeuBot](https://github.com/neubot/neubot-port-macosx).
